### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by simon-p-r** [AdrieanKhisbe/configue#1]
Hi

I am wondering what sort of config this plugin is designed for.  Plugins are called after hapi options are passed to its api so cannot be used to configure much with internals of hapi such as server options or server connections.

Thanks
Simon

**Comment by AdrieanKhisbe** [comment]
@simon-p-r, 
that's indeed one of the plugin weakness, that it cannot so far configure the `Hapi.Server` and `connection`
However it already enable you to configure other plugins such as `bell` for authentification.

---

I have in plan to extend the plugin, so that you can use it to do that:

``` js

const Hapi = require('hapi');
const Configue = require('hapi-configue')(options);

const server = new Hapi.Server(Configue.serverConfig());
server.connection(Configue.connexionConfig());

server.register({register: Configue}, (err) => {
    // ...
    });

```

**Comment by simon-p-r** [comment]
Have you seen confidence module? This is written by the hapi team. Interested to see which way this module goes

**Comment by AdrieanKhisbe** [comment]
Yep Yep, I already saw `Confidence` which is a very good plugin.

They do not cover the same use case.

>  a configuration document format, an API, and a foundation for A/B testing

But being able to interoperate them is a good idea. :)
(loading confidence format, and resolving the config from filters and co :) )

**Comment by AdrieanKhisbe** [comment]
héhé  :trollface: 

```
        KEEP
     CONFIDENCE
         AND 
      CONFIGUE 
        HAPI
```

**Comment by AdrieanKhisbe** [comment]
Hey Hey @simon-p-r 
with major refactor (that had been pending for too long), I made Configue far more feature-full outside of hapi.

Tell me if you have other suggestions ! 
(configue format handling is one of feature that will come some day)

(I have some roadmap non paper)

**Comment by simon-p-r** [comment]
I say your gitter message talking about these changes. I am currently trying to use within my application and will give you some feedback. I like changes so far.

**Comment by AdrieanKhisbe** [comment]
:smiley: 
feel free to contact me if you have any question.
(and post issue for feature request/suggestion)

**Comment by AdrieanKhisbe** [comment]
@simon-p-r Shall I close the issue?

**Comment by AdrieanKhisbe** [comment]
@simon-p-r Will soon close the issue unless i have news from your side. =)

**Comment by simon-p-r** [comment]
Hey @AdrieanKhisbe I never got round to testing, sorry for feedback.  If I have any in future I will re-open issue
