### ISSUE TITLE
Possible bug: normalize and env whitelist don't play nice together

### ISSUE THREAD

**Issue by mringer** [AdrieanKhisbe/configue#5]
## Issue description

Hi, I've been trying out configue for a project I'm working on. So far it's been good, thanks! 

I did notice one thing that looks to be a corner case not covered by your tests. It appears that the **_normalize_** option and the **_env whitelist_** may not play well together. When I attempt to use both the configue.get returns 'undefined' for any whitelisted envars. 

## version
```
"configue": "^1.0.0-rc.4",
```
## Failing Unit Test in Lab 
```
 it('normalize works with the env whitelist option', (done) => {
    process.env.NO_SEP = 'no sep';
    const configue = new Configue({
      normalize: 'camelCase',
      env: {
        whitelist: ['NO_SEP']
      },
    });
    process.env.NO_SEP = undefined;
    expect(configue.get('noSep')).to.equal('no sep');
    done();
  });
```

## Passing Unit Test in Lab 
```
 it('normalize works by itself', (done) => {
    process.env.NO_SEP = 'no sep';
    const configue = new Configue({
      normalize: 'camelCase',
      env: {
        // whitelist: ['NO_SEP']
      },
    });
    process.env.NO_SEP = undefined;
    expect(configue.get('noSep')).to.equal('no sep');
    done();
  });
```

**Comment by AdrieanKhisbe** [comment]
Thanks a lot @mringer for your detailled report! =) awesome!

Yes indeed, I haven't thought of that corner case. Seems like the whitelisting operate on the transformed value in nconf.
If so I think I could fix that by applying the normalizer to the provided whitelist.

I'm going to investigate in the evening and I come back to you, maybe with a new rc :)

**Comment by mringer** [comment]
Awesome, glad to help. I'll be sure to post anything else I find. Really enjoying the library, thanks again!

**Comment by AdrieanKhisbe** [comment]
@mringer Just published the release candidate 5. 😃

**Comment by mringer** [comment]
Awesome, I'll have a look, thanks!

**Comment by AdrieanKhisbe** [comment]
Hey @mringer , I just release Configue 1.0.0 if you want to have a look 😉

**Comment by mringer** [comment]
Hi @AdrieanKhisbe, 1.0.0 looks good, the whitelist seems to be working for me. I did find one thing with nested variables and normalize. I'll post a separate issue. 

Thanks!
