### ISSUE TITLE
Bug: Normalize doesn't transform nested variables in envar/argv

### ISSUE THREAD

**Issue by mringer** [AdrieanKhisbe/configue#6]
# Description of issue

Envars and argv provided to configue which utilize the 'separator' feature for nested config json objects do not transform the names of nested variables. So a argv or envar such as deep__four_two, should yield  {deep: { fourTwo: '42' }} but instead yields {deep: { four_two: '42' }}.

# Steps to reproduce. (Failing unit test)

```
        it('get nested, normalized value with underscores as a separator', (done) => {
            process.env.deep__four_two = '42';
            const configue = Configue({env: {normalize: true}, separator: '__'});
            // FIXIT: deep is { four_two: '42' } should be { fourTwo: '42' }
            expect(configue.get('deep.fourTwo')).to.equal('42');
            done();
        });
```

[full example in my fork](https://github.com/mringer/configue/commit/0e801dca5015fded98095ae73d75d94870ac7b49)

I may poke around and see if I can contribute a fix unless one is obvious to you or this is expected behavior.

Thanks!

**Comment by AdrieanKhisbe** [comment]
Hey @mringer !
It looks like you do not activate the noramlise feature in a proper manner, this is a global option and it should be provided with a case value: (here `camelCase`)
I had this covered with a test: https://github.com/AdrieanKhisbe/configue/blob/master/test/config-core-spec.js#L387

**Comment by mringer** [comment]
Shure enough, you're right! My configuration was in error. Thanks!

**Comment by AdrieanKhisbe** [comment]
you're welcome :)
